/**
 * Catalogue of supported countries.
 *
 * The object literals follow the exact spec from
 * `D:\Zyrix Hub\claude_code_sprint_3.txt` §1. When adding a new country,
 * update the `CountryCode` / `Currency` unions in `src/types/country.ts`
 * first so the compiler guides the rest of the change.
 */

import type { Country, CountryCode } from '../types/country';

export const SUPPORTED_COUNTRIES: readonly Country[] = [
  {
    code: 'SA',
    name: {
      ar: 'المملكة العربية السعودية',
      en: 'Saudi Arabia',
      tr: 'Suudi Arabistan',
    },
    flag: '🇸🇦',
    currency: 'SAR',
    currencySymbol: 'ر.س',
    currencyDecimals: 2,
    taxSystem: 'ZATCA',
    taxRate: 15,
    taxName: { ar: 'ضريبة القيمة المضافة', en: 'VAT', tr: 'KDV' },
    taxIdLabel: { ar: 'الرقم الضريبي', en: 'Tax ID', tr: 'Vergi No' },
    taxIdLength: 15,
    commercialRegLabel: {
      ar: 'السجل التجاري',
      en: 'Commercial Registration',
      tr: 'Ticaret Sicili',
    },
    phoneCode: '+966',
    phoneLength: 9,
    paymentMethods: [
      'mada',
      'stcpay',
      'applepay',
      'visa',
      'mastercard',
      'bank_transfer',
      'cash',
    ],
    dateFormat: 'dd/MM/yyyy',
    weekStart: 0,
    calendar: 'gregorian+hijri',
    regions: [
      'الرياض',
      'مكة المكرمة',
      'المدينة المنورة',
      'القصيم',
      'الشرقية',
      'عسير',
      'تبوك',
      'حائل',
      'الحدود الشمالية',
      'جازان',
      'نجران',
      'الباحة',
      'الجوف',
    ],
    language: 'ar',
    rtl: true,
    complianceRequirements: ['ZATCA_Phase2', 'PDPL'],
    weekend: ['Friday', 'Saturday'],
  },
  {
    code: 'AE',
    name: { ar: 'الإمارات العربية المتحدة', en: 'UAE', tr: 'BAE' },
    flag: '🇦🇪',
    currency: 'AED',
    currencySymbol: 'د.إ',
    currencyDecimals: 2,
    taxSystem: 'UAE_VAT',
    taxRate: 5,
    taxName: { ar: 'ضريبة القيمة المضافة', en: 'VAT', tr: 'KDV' },
    taxIdLabel: { ar: 'الرقم الضريبي', en: 'TRN', tr: 'Vergi No' },
    taxIdLength: 15,
    commercialRegLabel: {
      ar: 'الرخصة التجارية',
      en: 'Trade License',
      tr: 'Ticaret Lisansı',
    },
    phoneCode: '+971',
    phoneLength: 9,
    paymentMethods: [
      'visa',
      'mastercard',
      'applepay',
      'tabby',
      'tamara',
      'bank_transfer',
      'cash',
    ],
    dateFormat: 'dd/MM/yyyy',
    weekStart: 1,
    calendar: 'gregorian+hijri',
    regions: [
      'أبوظبي',
      'دبي',
      'الشارقة',
      'عجمان',
      'رأس الخيمة',
      'الفجيرة',
      'أم القيوين',
    ],
    language: 'ar',
    rtl: true,
    complianceRequirements: ['UAE_VAT', 'PDPL_UAE'],
    weekend: ['Saturday', 'Sunday'],
  },
  {
    code: 'KW',
    name: { ar: 'الكويت', en: 'Kuwait', tr: 'Kuveyt' },
    flag: '🇰🇼',
    currency: 'KWD',
    currencySymbol: 'د.ك',
    currencyDecimals: 3,
    taxSystem: 'none',
    taxRate: 0,
    taxName: { ar: '', en: '', tr: '' },
    phoneCode: '+965',
    phoneLength: 8,
    paymentMethods: [
      'knet',
      'visa',
      'mastercard',
      'applepay',
      'bank_transfer',
      'cash',
    ],
    dateFormat: 'dd/MM/yyyy',
    weekStart: 0,
    regions: [
      'الكويت',
      'حولي',
      'الفروانية',
      'مبارك الكبير',
      'الأحمدي',
      'الجهراء',
    ],
    language: 'ar',
    rtl: true,
    complianceRequirements: [],
    weekend: ['Friday', 'Saturday'],
  },
  {
    code: 'QA',
    name: { ar: 'قطر', en: 'Qatar', tr: 'Katar' },
    flag: '🇶🇦',
    currency: 'QAR',
    currencySymbol: 'ر.ق',
    currencyDecimals: 2,
    taxSystem: 'none',
    taxRate: 0,
    taxName: { ar: '', en: '', tr: '' },
    phoneCode: '+974',
    phoneLength: 8,
    paymentMethods: [
      'visa',
      'mastercard',
      'applepay',
      'naps',
      'bank_transfer',
      'cash',
    ],
    dateFormat: 'dd/MM/yyyy',
    weekStart: 0,
    regions: [
      'الدوحة',
      'الريان',
      'الوكرة',
      'أم صلال',
      'الخور',
      'الشحانية',
      'الشمال',
    ],
    language: 'ar',
    rtl: true,
    weekend: ['Friday', 'Saturday'],
  },
  {
    code: 'EG',
    name: { ar: 'مصر', en: 'Egypt', tr: 'Mısır' },
    flag: '🇪🇬',
    currency: 'EGP',
    currencySymbol: 'ج.م',
    currencyDecimals: 2,
    taxSystem: 'Egypt_VAT',
    taxRate: 14,
    taxName: { ar: 'ضريبة القيمة المضافة', en: 'VAT', tr: 'KDV' },
    taxIdLabel: { ar: 'الرقم الضريبي', en: 'Tax ID', tr: 'Vergi No' },
    taxIdLength: 9,
    phoneCode: '+20',
    phoneLength: 10,
    paymentMethods: [
      'visa',
      'mastercard',
      'fawry',
      'vodafone_cash',
      'instapay',
      'bank_transfer',
      'cash',
    ],
    dateFormat: 'dd/MM/yyyy',
    weekStart: 0,
    regions: [
      'القاهرة',
      'الجيزة',
      'الإسكندرية',
      'الدقهلية',
      'الشرقية',
      'القليوبية',
      'كفر الشيخ',
      'الغربية',
      'المنوفية',
      'البحيرة',
      'الإسماعيلية',
      'بورسعيد',
      'السويس',
      'شمال سيناء',
      'جنوب سيناء',
      'الفيوم',
      'بني سويف',
      'المنيا',
      'أسيوط',
      'سوهاج',
      'قنا',
      'الأقصر',
      'أسوان',
      'البحر الأحمر',
      'الوادي الجديد',
      'مطروح',
      'دمياط',
    ],
    language: 'ar',
    rtl: true,
    complianceRequirements: ['Egypt_ETA'],
    weekend: ['Friday', 'Saturday'],
  },
  {
    code: 'TR',
    name: { ar: 'تركيا', en: 'Turkey', tr: 'Türkiye' },
    flag: '🇹🇷',
    currency: 'TRY',
    currencySymbol: '₺',
    currencyDecimals: 2,
    taxSystem: 'Turkey_eFatura',
    taxRate: 20,
    taxName: { ar: 'ضريبة القيمة المضافة', en: 'VAT', tr: 'KDV' },
    taxIdLabel: { ar: 'الرقم الضريبي', en: 'Tax ID', tr: 'VKN' },
    taxIdLength: 10,
    commercialRegLabel: {
      ar: 'السجل التجاري',
      en: 'Trade Registry',
      tr: 'Ticaret Sicili',
    },
    phoneCode: '+90',
    phoneLength: 10,
    paymentMethods: [
      'iyzico',
      'paytr',
      'visa',
      'mastercard',
      'troy',
      'bank_transfer',
      'cash',
    ],
    dateFormat: 'dd.MM.yyyy',
    weekStart: 1,
    regions: [
      'İstanbul',
      'Ankara',
      'İzmir',
      'Bursa',
      'Antalya',
      'Adana',
      'Gaziantep',
      'Konya',
      'Kayseri',
      'Mersin',
      'Diyarbakır',
      'Samsun',
      'Denizli',
      'Eskişehir',
      'Şanlıurfa',
      'Malatya',
      'Erzurum',
      'Van',
      'Batman',
      'Elazığ',
      'Erzincan',
      'Sakarya',
      'Trabzon',
      'Manisa',
      'Balıkesir',
    ],
    language: 'tr',
    rtl: false,
    complianceRequirements: ['eFatura_UBL_TR', 'KVKK'],
    weekend: ['Saturday', 'Sunday'],
  },
  {
    code: 'BH',
    name: { ar: 'البحرين', en: 'Bahrain', tr: 'Bahreyn' },
    flag: '🇧🇭',
    currency: 'BHD',
    currencySymbol: 'د.ب',
    currencyDecimals: 3,
    taxSystem: 'Bahrain_VAT',
    taxRate: 10,
    taxName: { ar: 'ضريبة القيمة المضافة', en: 'VAT', tr: 'KDV' },
    taxIdLabel: { ar: 'الرقم الضريبي', en: 'Tax ID', tr: 'Vergi No' },
    taxIdLength: 9,
    phoneCode: '+973',
    phoneLength: 8,
    paymentMethods: [
      'benefit',
      'visa',
      'mastercard',
      'applepay',
      'bank_transfer',
      'cash',
    ],
    dateFormat: 'dd/MM/yyyy',
    weekStart: 0,
    regions: [
      'المنامة',
      'المحرق',
      'الرفاع',
      'عيسى',
      'مدينة حمد',
      'سترة',
      'مدينة زايد',
    ],
    language: 'ar',
    rtl: true,
    weekend: ['Friday', 'Saturday'],
  },
  {
    code: 'OM',
    name: { ar: 'عمان', en: 'Oman', tr: 'Umman' },
    flag: '🇴🇲',
    currency: 'OMR',
    currencySymbol: 'ر.ع',
    currencyDecimals: 3,
    taxSystem: 'Oman_VAT',
    taxRate: 5,
    taxName: { ar: 'ضريبة القيمة المضافة', en: 'VAT', tr: 'KDV' },
    taxIdLabel: { ar: 'الرقم الضريبي', en: 'Tax ID', tr: 'Vergi No' },
    taxIdLength: 8,
    phoneCode: '+968',
    phoneLength: 8,
    paymentMethods: [
      'thawani',
      'omannet',
      'visa',
      'mastercard',
      'bank_transfer',
      'cash',
    ],
    dateFormat: 'dd/MM/yyyy',
    weekStart: 0,
    regions: [
      'مسقط',
      'ظفار',
      'الباطنة شمال',
      'الباطنة جنوب',
      'الظاهرة',
      'الداخلية',
      'الشرقية شمال',
      'الشرقية جنوب',
      'الوسطى',
      'مسندم',
      'البريمي',
    ],
    language: 'ar',
    rtl: true,
    weekend: ['Friday', 'Saturday'],
  },
  {
    code: 'JO',
    name: { ar: 'الأردن', en: 'Jordan', tr: 'Ürdün' },
    flag: '🇯🇴',
    currency: 'JOD',
    currencySymbol: 'د.أ',
    currencyDecimals: 3,
    taxSystem: 'Jordan_GST',
    taxRate: 16,
    taxName: {
      ar: 'ضريبة المبيعات العامة',
      en: 'GST',
      tr: 'Genel Satış Vergisi',
    },
    taxIdLabel: { ar: 'الرقم الضريبي', en: 'Tax ID', tr: 'Vergi No' },
    taxIdLength: 9,
    phoneCode: '+962',
    phoneLength: 9,
    paymentMethods: ['cliq', 'visa', 'mastercard', 'bank_transfer', 'cash'],
    dateFormat: 'dd/MM/yyyy',
    weekStart: 0,
    regions: [
      'عمّان',
      'إربد',
      'الزرقاء',
      'البلقاء',
      'الكرك',
      'مأدبا',
      'جرش',
      'عجلون',
      'المفرق',
      'الطفيلة',
      'معان',
      'العقبة',
    ],
    language: 'ar',
    rtl: true,
    weekend: ['Friday', 'Saturday'],
  },
];

export const DEFAULT_COUNTRY_CODE: CountryCode = 'SA';

export const findCountry = (code: CountryCode | null | undefined): Country => {
  const match = SUPPORTED_COUNTRIES.find((c) => c.code === code);
  return (
    match ??
    (SUPPORTED_COUNTRIES.find((c) => c.code === DEFAULT_COUNTRY_CODE) as Country)
  );
};

export const isCountryCode = (value: string | null | undefined): value is CountryCode =>
  !!value && SUPPORTED_COUNTRIES.some((c) => c.code === value);
