/**
 * Deterministic mock dataset for the admin panel. Used until the
 * platform admin endpoints are wired into the backend.
 */

import type {
  AdminSummary,
  AdminUser,
  AuditLogEntry,
  Company,
  ComplianceExport,
  FeatureFlag,
  IPRule,
  Plan,
  RetentionPolicy,
  SCIMToken,
  SystemStats,
} from '../types/admin';

export const MOCK_COMPANIES: readonly Company[] = [
  {
    id: 'comp_101',
    name: 'Al-Salam Distribution',
    ownerId: 'user_111',
    ownerName: 'Ahmed Al-Salam',
    ownerEmail: 'ahmed@alsalam.sa',
    country: 'SA',
    plan: 'business',
    planId: 'plan_business',
    status: 'active',
    usersCount: 12,
    customersCount: 142,
    mrr: 49,
    createdAt: '2024-06-12T10:00:00Z',
    lastActivityAt: '2026-04-22T15:00:00Z',
  },
  {
    id: 'comp_102',
    name: 'Elma Retail',
    ownerId: 'user_112',
    ownerName: 'Layla Hassan',
    ownerEmail: 'layla@elma.ae',
    country: 'AE',
    plan: 'starter',
    planId: 'plan_starter',
    status: 'active',
    usersCount: 6,
    customersCount: 58,
    mrr: 19,
    createdAt: '2024-11-02T09:15:00Z',
    lastActivityAt: '2026-04-22T08:30:00Z',
  },
  {
    id: 'comp_103',
    name: 'Nova Medikal',
    ownerId: 'user_113',
    ownerName: 'Selin Aydın',
    ownerEmail: 'selin@novamedikal.com.tr',
    country: 'TR',
    plan: 'enterprise',
    planId: 'plan_enterprise',
    status: 'active',
    usersCount: 38,
    customersCount: 412,
    mrr: 245,
    createdAt: '2025-01-18T11:30:00Z',
    lastActivityAt: '2026-04-22T17:10:00Z',
  },
  {
    id: 'comp_104',
    name: 'Masr Foods',
    ownerId: 'user_114',
    ownerName: 'Karim Mahmoud',
    ownerEmail: 'karim@masrfoods.eg',
    country: 'EG',
    plan: 'free',
    planId: 'plan_free',
    status: 'pending',
    usersCount: 2,
    customersCount: 11,
    mrr: 0,
    createdAt: '2026-04-12T08:00:00Z',
    lastActivityAt: '2026-04-21T11:00:00Z',
  },
  {
    id: 'comp_105',
    name: 'Gulf Tech',
    ownerId: 'user_115',
    ownerName: 'Mariam Al-Sabah',
    ownerEmail: 'mariam@gulftech.kw',
    country: 'KW',
    plan: 'business',
    planId: 'plan_business',
    status: 'suspended',
    usersCount: 9,
    customersCount: 67,
    mrr: 49,
    createdAt: '2024-09-22T14:10:00Z',
    suspendedAt: '2026-04-15T08:00:00Z',
    suspensionReason: 'Payment overdue 60+ days',
    lastActivityAt: '2026-04-15T08:00:00Z',
  },
];

export const MOCK_ADMIN_USERS: readonly AdminUser[] = [
  {
    id: 'user_111',
    name: 'Ahmed Al-Salam',
    email: 'ahmed@alsalam.sa',
    role: 'merchant_owner',
    companyId: 'comp_101',
    companyName: 'Al-Salam Distribution',
    status: 'active',
    lastLoginAt: '2026-04-22T14:00:00Z',
    createdAt: '2024-06-12T10:00:00Z',
    avatarInitials: 'AA',
  },
  {
    id: 'user_112',
    name: 'Layla Hassan',
    email: 'layla@elma.ae',
    role: 'merchant_owner',
    companyId: 'comp_102',
    companyName: 'Elma Retail',
    status: 'active',
    lastLoginAt: '2026-04-22T08:00:00Z',
    createdAt: '2024-11-02T09:15:00Z',
    avatarInitials: 'LH',
  },
  {
    id: 'user_113',
    name: 'Selin Aydın',
    email: 'selin@novamedikal.com.tr',
    role: 'merchant_owner',
    companyId: 'comp_103',
    companyName: 'Nova Medikal',
    status: 'active',
    lastLoginAt: '2026-04-22T17:00:00Z',
    createdAt: '2025-01-18T11:30:00Z',
    avatarInitials: 'SA',
  },
  {
    id: 'user_201',
    name: 'Fatima Hassan',
    email: 'fatima@nova.tr',
    role: 'merchant_manager',
    companyId: 'comp_103',
    companyName: 'Nova Medikal',
    status: 'active',
    lastLoginAt: '2026-04-21T13:45:00Z',
    createdAt: '2025-02-01T09:00:00Z',
    avatarInitials: 'FH',
  },
  {
    id: 'user_999',
    name: 'Mehmet Fatih',
    email: 'admin@zyrix.co',
    role: 'super_admin',
    companyId: null,
    companyName: null,
    status: 'active',
    lastLoginAt: '2026-04-22T18:00:00Z',
    createdAt: '2024-01-01T00:00:00Z',
    avatarInitials: 'MF',
  },
];

export const MOCK_FEATURE_FLAGS: readonly FeatureFlag[] = [
  // Sales
  { key: 'customers', name: 'Customer management', category: 'sales', enabled: true, defaultEnabledFor: 'all' },
  { key: 'deals', name: 'Sales pipeline', category: 'sales', enabled: true, defaultEnabledFor: 'all' },
  { key: 'quotes', name: 'Quote builder', category: 'sales', enabled: true, defaultEnabledFor: 'starter' },
  { key: 'contracts', name: 'Contract management', category: 'sales', enabled: true, defaultEnabledFor: 'business' },
  { key: 'commissions', name: 'Commissions tracking', category: 'sales', enabled: true, defaultEnabledFor: 'business' },
  { key: 'territories', name: 'Sales territories', category: 'sales', enabled: true, defaultEnabledFor: 'business' },
  { key: 'forecast', name: 'AI sales forecast', category: 'sales', enabled: true, defaultEnabledFor: 'business' },
  // Growth
  { key: 'loyalty', name: 'Loyalty programme', category: 'growth', enabled: true, defaultEnabledFor: 'starter' },
  { key: 'campaigns', name: 'Marketing campaigns', category: 'growth', enabled: true, defaultEnabledFor: 'starter' },
  // AI
  { key: 'ai_cfo', name: 'AI CFO', category: 'ai', enabled: true, defaultEnabledFor: 'business' },
  { key: 'ai_workflows', name: 'AI workflows', category: 'ai', enabled: true, defaultEnabledFor: 'business' },
  { key: 'ai_builder', name: 'AI builder', category: 'ai', enabled: true, defaultEnabledFor: 'business' },
  { key: 'lead_scoring', name: 'Predictive lead scoring', category: 'ai', enabled: true, defaultEnabledFor: 'business' },
  { key: 'conversation_intel', name: 'Conversation intelligence', category: 'ai', enabled: true, defaultEnabledFor: 'enterprise' },
  { key: 'meeting_intel', name: 'Meeting intelligence', category: 'ai', enabled: true, defaultEnabledFor: 'enterprise' },
  { key: 'duplicate_ai', name: 'Smart duplicate detection', category: 'ai', enabled: true, defaultEnabledFor: 'business' },
  // Operations
  { key: 'payments', name: 'Payments + links', category: 'operations', enabled: true, defaultEnabledFor: 'all' },
  { key: 'refunds', name: 'Refund processing', category: 'operations', enabled: true, defaultEnabledFor: 'starter' },
  { key: 'reports_advanced', name: 'Advanced reports', category: 'operations', enabled: true, defaultEnabledFor: 'business' },
  // Security & Compliance
  { key: 'ip_allowlist', name: 'IP allowlist', category: 'security', enabled: true, defaultEnabledFor: 'enterprise' },
  { key: 'scim', name: 'SCIM provisioning', category: 'security', enabled: true, defaultEnabledFor: 'enterprise' },
  { key: 'audit_export', name: 'Audit log export', category: 'security', enabled: true, defaultEnabledFor: 'business' },
  { key: 'gdpr_exports', name: 'GDPR/CCPA/PDPL exports', category: 'security', enabled: true, defaultEnabledFor: 'business' },
  { key: 'two_factor', name: 'Two-factor auth (TOTP)', category: 'security', enabled: true, defaultEnabledFor: 'all' },
  { key: 'sso_saml', name: 'SAML SSO', category: 'security', enabled: true, defaultEnabledFor: 'enterprise' },
  // Tax compliance
  { key: 'zatca_efatura', name: 'ZATCA + e-Fatura', category: 'taxCompliance', enabled: true, defaultEnabledFor: 'business' },
  // Integrations
  { key: 'whatsapp', name: 'WhatsApp Business', category: 'integrations', enabled: true, defaultEnabledFor: 'starter' },
  { key: 'webhooks', name: 'Outbound webhooks', category: 'integrations', enabled: true, defaultEnabledFor: 'business' },
  // Platform
  { key: 'multi_company', name: 'Multi-company switcher', category: 'platform', enabled: true, defaultEnabledFor: 'enterprise' },
  // Advanced
  { key: 'custom_fields', name: 'Unlimited custom fields', category: 'advanced', enabled: true, defaultEnabledFor: 'business' },
  { key: 'ai_limits_high', name: 'High AI rate limits', category: 'advanced', enabled: true, defaultEnabledFor: 'enterprise' },
  // Experience
  { key: 'white_label', name: 'White-label branding', category: 'experience', enabled: true, defaultEnabledFor: 'enterprise' },
  { key: 'priority_support', name: 'Priority support', category: 'experience', enabled: true, defaultEnabledFor: 'enterprise' },
];

export const MOCK_PLANS: readonly Plan[] = [
  {
    id: 'plan_free',
    name: 'Free',
    slug: 'free',
    priceMonthly: 0,
    priceAnnually: 0,
    description: 'Get started for free.',
    features: ['customers', 'deals', 'payments', 'two_factor'],
    limits: { users: 5, customers: 100, storageGB: 1, apiCallsPerMonth: 5_000 },
    active: true,
    order: 0,
    companiesCount: 1,
  },
  {
    id: 'plan_starter',
    name: 'Starter',
    slug: 'starter',
    priceMonthly: 19,
    priceAnnually: 190,
    description: 'For small teams ready to grow.',
    features: ['customers', 'deals', 'quotes', 'loyalty', 'campaigns', 'whatsapp', 'refunds'],
    limits: { users: 15, customers: 1_000, storageGB: 10, apiCallsPerMonth: 50_000 },
    active: true,
    order: 1,
    companiesCount: 1,
  },
  {
    id: 'plan_business',
    name: 'Business',
    slug: 'business',
    priceMonthly: 49,
    priceAnnually: 490,
    description: 'For mature operations.',
    features: [
      'customers',
      'deals',
      'quotes',
      'contracts',
      'commissions',
      'territories',
      'forecast',
      'loyalty',
      'campaigns',
      'ai_cfo',
      'ai_workflows',
      'ai_builder',
      'lead_scoring',
      'duplicate_ai',
      'reports_advanced',
      'audit_export',
      'gdpr_exports',
      'zatca_efatura',
      'whatsapp',
      'webhooks',
      'custom_fields',
    ],
    limits: { users: -1, customers: 10_000, storageGB: 50, apiCallsPerMonth: 250_000 },
    active: true,
    order: 2,
    companiesCount: 2,
  },
  {
    id: 'plan_enterprise',
    name: 'Enterprise',
    slug: 'enterprise',
    priceMonthly: 245,
    priceAnnually: 2_450,
    description: 'Tailored to enterprise compliance.',
    features: ['*'],
    limits: { users: -1, customers: -1, storageGB: 500, apiCallsPerMonth: 2_500_000 },
    active: true,
    order: 3,
    companiesCount: 1,
  },
];

export const MOCK_AUDIT_LOG: readonly AuditLogEntry[] = [
  {
    id: 'al_001',
    timestamp: '2026-04-22T17:30:00Z',
    userId: 'user_999',
    userName: 'Mehmet Fatih',
    companyId: null,
    companyName: 'Zyrix Platform',
    action: 'feature_flag.update',
    resource: 'feature_flag',
    resourceId: 'lead_scoring',
    ipAddress: '212.118.45.12',
    severity: 'info',
  },
  {
    id: 'al_002',
    timestamp: '2026-04-22T16:42:00Z',
    userId: 'user_111',
    userName: 'Ahmed Al-Salam',
    companyId: 'comp_101',
    companyName: 'Al-Salam Distribution',
    action: 'invoice.submit_zatca',
    resource: 'invoice',
    resourceId: 'inv_001',
    ipAddress: '85.140.23.99',
    severity: 'info',
  },
  {
    id: 'al_003',
    timestamp: '2026-04-22T13:10:00Z',
    userId: 'user_115',
    userName: 'Mariam Al-Sabah',
    companyId: 'comp_105',
    companyName: 'Gulf Tech',
    action: 'login.failed',
    resource: 'session',
    ipAddress: '37.123.55.21',
    severity: 'warning',
  },
  {
    id: 'al_004',
    timestamp: '2026-04-22T09:00:00Z',
    userId: 'user_999',
    userName: 'Mehmet Fatih',
    companyId: 'comp_105',
    companyName: 'Gulf Tech',
    action: 'company.suspend',
    resource: 'company',
    resourceId: 'comp_105',
    ipAddress: '212.118.45.12',
    metadata: { reason: 'Payment overdue 60+ days' },
    severity: 'critical',
  },
];

export const MOCK_SYSTEM_STATS: SystemStats = {
  apiResponseTime: { avg: 142, p95: 312, p99: 540 },
  activeSessions: 1284,
  dbConnections: { active: 87, max: 200 },
  storageUsedGB: 412,
  storageQuotaGB: 1024,
  errorRate: 0.43,
  uptimePercent: 99.97,
  trafficByHour: Array.from({ length: 12 }, (_, idx) => ({
    hour: `${(idx * 2).toString().padStart(2, '0')}:00`,
    requests: 1200 + Math.round(800 * Math.sin(idx / 2)),
  })),
  responseTrend: Array.from({ length: 12 }, (_, idx) => ({
    time: `H-${12 - idx}`,
    ms: 110 + Math.round(40 * Math.sin(idx / 2)),
  })),
  errorTrend: Array.from({ length: 12 }, (_, idx) => ({
    time: `H-${12 - idx}`,
    rate: +(0.2 + Math.abs(Math.sin(idx)) * 0.6).toFixed(2),
  })),
  incidents: [
    {
      id: 'inc_001',
      title: 'Elevated 5xx on payments service',
      severity: 'warning',
      date: '2026-04-19T11:30:00Z',
    },
    {
      id: 'inc_002',
      title: 'Database failover (replica promoted)',
      severity: 'info',
      date: '2026-04-15T03:10:00Z',
    },
  ],
};

export const MOCK_RETENTION_POLICIES: readonly RetentionPolicy[] = [
  {
    id: 'rp_customers',
    entityType: 'customer',
    retentionDays: 2555,
    legalHoldActive: false,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'rp_audit',
    entityType: 'audit_log',
    retentionDays: 1825,
    legalHoldActive: false,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'rp_messages',
    entityType: 'message',
    retentionDays: 365,
    legalHoldActive: false,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'rp_invoices',
    entityType: 'invoice',
    retentionDays: 3650,
    legalHoldActive: true,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'rp_payments',
    entityType: 'payment',
    retentionDays: 3650,
    legalHoldActive: false,
    createdAt: '2025-01-01T00:00:00Z',
  },
];

export const MOCK_IP_RULES: readonly IPRule[] = [
  {
    id: 'ip_001',
    companyId: null,
    cidr: '0.0.0.0/0',
    description: 'Default platform allow (all internet)',
    mode: 'all',
    exceptions: [],
    mobileBypass: true,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ip_002',
    companyId: 'comp_103',
    companyName: 'Nova Medikal',
    cidr: '85.140.23.0/24',
    description: 'İstanbul HQ network',
    mode: 'employees_only',
    exceptions: ['merchant_owner'],
    mobileBypass: true,
    createdAt: '2026-02-12T08:00:00Z',
  },
];

export const MOCK_SCIM_TOKENS: readonly SCIMToken[] = [
  {
    id: 'sc_001',
    companyId: 'comp_103',
    companyName: 'Nova Medikal',
    tokenPreview: 'scim_••••••••f4a9',
    scope: 'read_write',
    createdAt: '2026-03-01T09:00:00Z',
    lastUsedAt: '2026-04-22T07:30:00Z',
    expiresAt: '2027-03-01T09:00:00Z',
  },
];

export const MOCK_COMPLIANCE_EXPORTS: readonly ComplianceExport[] = [
  {
    id: 'ce_001',
    customerId: 'cus_001',
    customerName: 'Al-Salam Distribution',
    companyId: 'comp_101',
    companyName: 'Al-Salam Distribution',
    type: 'pdpl',
    status: 'ready',
    requestedAt: '2026-04-18T10:00:00Z',
    readyAt: '2026-04-19T08:30:00Z',
    downloadUrl: 'https://api.crm.zyrix.co/exports/ce_001.zip',
    expiresAt: '2026-05-03T08:30:00Z',
    urgency: 'standard',
  },
  {
    id: 'ce_002',
    customerId: 'cus_003',
    customerName: 'Nova Medikal',
    companyId: 'comp_103',
    companyName: 'Nova Medikal',
    type: 'gdpr',
    status: 'processing',
    requestedAt: '2026-04-22T11:00:00Z',
    expiresAt: '2026-05-22T00:00:00Z',
    urgency: 'rush',
  },
];

export const buildAdminSummary = (): AdminSummary => ({
  totalCompanies: MOCK_COMPANIES.length,
  totalCompaniesDelta: 12,
  activeUsers: MOCK_ADMIN_USERS.filter((user) => user.status === 'active').length,
  monthlyRecurringRevenue: MOCK_COMPANIES.reduce(
    (sum, company) => sum + company.mrr,
    0
  ),
  newSignupsToday: 3,
  signupsTrend: Array.from({ length: 14 }, (_, idx) => ({
    date: `D-${14 - idx}`,
    count: 2 + Math.round(Math.abs(Math.sin(idx)) * 6),
  })),
  revenueTrend: Array.from({ length: 12 }, (_, idx) => ({
    month: `${idx + 1}/26`,
    amount: 18_400 + idx * 2_350 + Math.round(Math.abs(Math.cos(idx)) * 4_000),
  })),
  planDistribution: MOCK_PLANS.map((plan) => ({
    plan: plan.slug,
    count: plan.companiesCount,
    share: Math.round(
      (plan.companiesCount /
        MOCK_PLANS.reduce((sum, p) => sum + p.companiesCount, 0)) *
        100
    ),
  })),
  topCompanies: MOCK_COMPANIES.slice()
    .sort((a, b) => b.mrr - a.mrr)
    .slice(0, 5)
    .map((company) => ({
      id: company.id,
      name: company.name,
      mrr: company.mrr,
    })),
  alerts: {
    overduePayments: 2,
    pendingTickets: 5,
    pendingCompliance: 1,
  },
  recentActivities: MOCK_AUDIT_LOG.slice(0, 5),
});
